//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsSession {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsSessionSoap", Namespace="http://tempuri.org/")]
    public partial class WsSession : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SA_CreateSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SA_UpdateSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SA_GetLastSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SA_GetSessionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsSession() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsSession_WsSession;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SA_CreateSessionCompletedEventHandler SA_CreateSessionCompleted;
        
        /// <remarks/>
        public event SA_UpdateSessionCompletedEventHandler SA_UpdateSessionCompleted;
        
        /// <remarks/>
        public event SA_GetLastSessionCompletedEventHandler SA_GetLastSessionCompleted;
        
        /// <remarks/>
        public event SA_GetSessionCompletedEventHandler SA_GetSessionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SA_CreateSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SA_CreateSession(long AF_Id) {
            object[] results = this.Invoke("SA_CreateSession", new object[] {
                        AF_Id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SA_CreateSessionAsync(long AF_Id) {
            this.SA_CreateSessionAsync(AF_Id, null);
        }
        
        /// <remarks/>
        public void SA_CreateSessionAsync(long AF_Id, object userState) {
            if ((this.SA_CreateSessionOperationCompleted == null)) {
                this.SA_CreateSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSA_CreateSessionOperationCompleted);
            }
            this.InvokeAsync("SA_CreateSession", new object[] {
                        AF_Id}, this.SA_CreateSessionOperationCompleted, userState);
        }
        
        private void OnSA_CreateSessionOperationCompleted(object arg) {
            if ((this.SA_CreateSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SA_CreateSessionCompleted(this, new SA_CreateSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SA_UpdateSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SA_UpdateSession(SessionAfiliado sa) {
            object[] results = this.Invoke("SA_UpdateSession", new object[] {
                        sa});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SA_UpdateSessionAsync(SessionAfiliado sa) {
            this.SA_UpdateSessionAsync(sa, null);
        }
        
        /// <remarks/>
        public void SA_UpdateSessionAsync(SessionAfiliado sa, object userState) {
            if ((this.SA_UpdateSessionOperationCompleted == null)) {
                this.SA_UpdateSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSA_UpdateSessionOperationCompleted);
            }
            this.InvokeAsync("SA_UpdateSession", new object[] {
                        sa}, this.SA_UpdateSessionOperationCompleted, userState);
        }
        
        private void OnSA_UpdateSessionOperationCompleted(object arg) {
            if ((this.SA_UpdateSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SA_UpdateSessionCompleted(this, new SA_UpdateSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SA_GetLastSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionAfiliado SA_GetLastSession(long AF_Id) {
            object[] results = this.Invoke("SA_GetLastSession", new object[] {
                        AF_Id});
            return ((SessionAfiliado)(results[0]));
        }
        
        /// <remarks/>
        public void SA_GetLastSessionAsync(long AF_Id) {
            this.SA_GetLastSessionAsync(AF_Id, null);
        }
        
        /// <remarks/>
        public void SA_GetLastSessionAsync(long AF_Id, object userState) {
            if ((this.SA_GetLastSessionOperationCompleted == null)) {
                this.SA_GetLastSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSA_GetLastSessionOperationCompleted);
            }
            this.InvokeAsync("SA_GetLastSession", new object[] {
                        AF_Id}, this.SA_GetLastSessionOperationCompleted, userState);
        }
        
        private void OnSA_GetLastSessionOperationCompleted(object arg) {
            if ((this.SA_GetLastSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SA_GetLastSessionCompleted(this, new SA_GetLastSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SA_GetSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionAfiliado SA_GetSession(string sesion) {
            object[] results = this.Invoke("SA_GetSession", new object[] {
                        sesion});
            return ((SessionAfiliado)(results[0]));
        }
        
        /// <remarks/>
        public void SA_GetSessionAsync(string sesion) {
            this.SA_GetSessionAsync(sesion, null);
        }
        
        /// <remarks/>
        public void SA_GetSessionAsync(string sesion, object userState) {
            if ((this.SA_GetSessionOperationCompleted == null)) {
                this.SA_GetSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSA_GetSessionOperationCompleted);
            }
            this.InvokeAsync("SA_GetSession", new object[] {
                        sesion}, this.SA_GetSessionOperationCompleted, userState);
        }
        
        private void OnSA_GetSessionOperationCompleted(object arg) {
            if ((this.SA_GetSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SA_GetSessionCompleted(this, new SA_GetSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SessionAfiliado {
        
        private long aF_IdField;
        
        private string sesionField;
        
        private System.DateTime tiempoInicioField;
        
        private System.DateTime tiempoFinField;
        
        private string sES_CodStatusField;
        
        /// <comentarios/>
        public long AF_Id {
            get {
                return this.aF_IdField;
            }
            set {
                this.aF_IdField = value;
            }
        }
        
        /// <comentarios/>
        public string Sesion {
            get {
                return this.sesionField;
            }
            set {
                this.sesionField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime TiempoInicio {
            get {
                return this.tiempoInicioField;
            }
            set {
                this.tiempoInicioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime TiempoFin {
            get {
                return this.tiempoFinField;
            }
            set {
                this.tiempoFinField = value;
            }
        }
        
        /// <comentarios/>
        public string SES_CodStatus {
            get {
                return this.sES_CodStatusField;
            }
            set {
                this.sES_CodStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SA_CreateSessionCompletedEventHandler(object sender, SA_CreateSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SA_CreateSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SA_CreateSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SA_UpdateSessionCompletedEventHandler(object sender, SA_UpdateSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SA_UpdateSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SA_UpdateSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SA_GetLastSessionCompletedEventHandler(object sender, SA_GetLastSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SA_GetLastSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SA_GetLastSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SessionAfiliado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SessionAfiliado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SA_GetSessionCompletedEventHandler(object sender, SA_GetSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SA_GetSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SA_GetSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SessionAfiliado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SessionAfiliado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591