//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsGlobal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsGlobalSoap", Namespace="http://tempuri.org/")]
    public partial class WsGlobal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EstatusGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Def_LovGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogRefBankAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogRegUsAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogTransAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback BDI_TipoTransaccionGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback BDI_TipoTransaccionLogGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback BDI_TipoTransaccionPadreGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogTransGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogTransDiarioAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroOperDiariasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProveedoresGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgenciasGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgenciaGetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TiposFindOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankGetByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankGetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankGetByBinOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroReferenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroReferenciaCrediCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChkBineCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTipoTarjetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BDI_DatosCorreoGetByDC_CodTransOperationCompleted;
        
        private System.Threading.SendOrPostCallback DiasPasswordgetOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSendMsgOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsGlobal() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsGlobal_WsGlobal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EstatusGetCompletedEventHandler EstatusGetCompleted;
        
        /// <remarks/>
        public event Def_LovGetCompletedEventHandler Def_LovGetCompleted;
        
        /// <remarks/>
        public event LogRefBankAddCompletedEventHandler LogRefBankAddCompleted;
        
        /// <remarks/>
        public event LogRegUsAddCompletedEventHandler LogRegUsAddCompleted;
        
        /// <remarks/>
        public event LogTransAddCompletedEventHandler LogTransAddCompleted;
        
        /// <remarks/>
        public event BDI_TipoTransaccionGetCompletedEventHandler BDI_TipoTransaccionGetCompleted;
        
        /// <remarks/>
        public event BDI_TipoTransaccionLogGetCompletedEventHandler BDI_TipoTransaccionLogGetCompleted;
        
        /// <remarks/>
        public event BDI_TipoTransaccionPadreGetCompletedEventHandler BDI_TipoTransaccionPadreGetCompleted;
        
        /// <remarks/>
        public event LogTransGetCompletedEventHandler LogTransGetCompleted;
        
        /// <remarks/>
        public event LogTransDiarioAddCompletedEventHandler LogTransDiarioAddCompleted;
        
        /// <remarks/>
        public event GetNumeroOperDiariasCompletedEventHandler GetNumeroOperDiariasCompleted;
        
        /// <remarks/>
        public event ProveedoresGetCompletedEventHandler ProveedoresGetCompleted;
        
        /// <remarks/>
        public event DeleteProductoCompletedEventHandler DeleteProductoCompleted;
        
        /// <remarks/>
        public event AgenciasGetCompletedEventHandler AgenciasGetCompleted;
        
        /// <remarks/>
        public event AgenciaGetByIdCompletedEventHandler AgenciaGetByIdCompleted;
        
        /// <remarks/>
        public event TiposFindCompletedEventHandler TiposFindCompleted;
        
        /// <remarks/>
        public event BankGetByTypeCompletedEventHandler BankGetByTypeCompleted;
        
        /// <remarks/>
        public event BankGetCompletedEventHandler BankGetCompleted;
        
        /// <remarks/>
        public event BankGetByIdCompletedEventHandler BankGetByIdCompleted;
        
        /// <remarks/>
        public event BankGetByBinCompletedEventHandler BankGetByBinCompleted;
        
        /// <remarks/>
        public event GetNumeroReferenciaCompletedEventHandler GetNumeroReferenciaCompleted;
        
        /// <remarks/>
        public event GetNumeroReferenciaCrediCardCompletedEventHandler GetNumeroReferenciaCrediCardCompleted;
        
        /// <remarks/>
        public event ChkBineCardCompletedEventHandler ChkBineCardCompleted;
        
        /// <remarks/>
        public event GetTipoTarjetasCompletedEventHandler GetTipoTarjetasCompleted;
        
        /// <remarks/>
        public event BDI_DatosCorreoGetByDC_CodTransCompletedEventHandler BDI_DatosCorreoGetByDC_CodTransCompleted;
        
        /// <remarks/>
        public event DiasPasswordgetCompletedEventHandler DiasPasswordgetCompleted;
        
        /// <remarks/>
        public event SaveSendMsgCompletedEventHandler SaveSendMsgCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstatusGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EstatusGet(int nES_IdIn) {
            object[] results = this.Invoke("EstatusGet", new object[] {
                        nES_IdIn});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EstatusGetAsync(int nES_IdIn) {
            this.EstatusGetAsync(nES_IdIn, null);
        }
        
        /// <remarks/>
        public void EstatusGetAsync(int nES_IdIn, object userState) {
            if ((this.EstatusGetOperationCompleted == null)) {
                this.EstatusGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstatusGetOperationCompleted);
            }
            this.InvokeAsync("EstatusGet", new object[] {
                        nES_IdIn}, this.EstatusGetOperationCompleted, userState);
        }
        
        private void OnEstatusGetOperationCompleted(object arg) {
            if ((this.EstatusGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstatusGetCompleted(this, new EstatusGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Def_LovGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Def_LovGet(int nCodTipoLovIn) {
            object[] results = this.Invoke("Def_LovGet", new object[] {
                        nCodTipoLovIn});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Def_LovGetAsync(int nCodTipoLovIn) {
            this.Def_LovGetAsync(nCodTipoLovIn, null);
        }
        
        /// <remarks/>
        public void Def_LovGetAsync(int nCodTipoLovIn, object userState) {
            if ((this.Def_LovGetOperationCompleted == null)) {
                this.Def_LovGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDef_LovGetOperationCompleted);
            }
            this.InvokeAsync("Def_LovGet", new object[] {
                        nCodTipoLovIn}, this.Def_LovGetOperationCompleted, userState);
        }
        
        private void OnDef_LovGetOperationCompleted(object arg) {
            if ((this.Def_LovGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Def_LovGetCompleted(this, new Def_LovGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogRefBankAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long LogRefBankAdd(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    string Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sTipoCuenta_Origen, 
                    string sCuenta_Origen, 
                    string sMonto, 
                    string sDirigidoA, 
                    string sFechaAperturaCta, 
                    string sSaldoPromediom, 
                    string sMesesRef, 
                    string sCifras, 
                    string sTipoRef, 
                    string sStatus) {
            object[] results = this.Invoke("LogRefBankAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sTipoCuenta_Origen,
                        sCuenta_Origen,
                        sMonto,
                        sDirigidoA,
                        sFechaAperturaCta,
                        sSaldoPromediom,
                        sMesesRef,
                        sCifras,
                        sTipoRef,
                        sStatus});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void LogRefBankAddAsync(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    string Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sTipoCuenta_Origen, 
                    string sCuenta_Origen, 
                    string sMonto, 
                    string sDirigidoA, 
                    string sFechaAperturaCta, 
                    string sSaldoPromediom, 
                    string sMesesRef, 
                    string sCifras, 
                    string sTipoRef, 
                    string sStatus) {
            this.LogRefBankAddAsync(nAF_Id, sAF_NombreUsuario, Fecha_Trans, sTime_Trans, sAF_IP, sCod_Trans, sTipoCuenta_Origen, sCuenta_Origen, sMonto, sDirigidoA, sFechaAperturaCta, sSaldoPromediom, sMesesRef, sCifras, sTipoRef, sStatus, null);
        }
        
        /// <remarks/>
        public void LogRefBankAddAsync(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    string Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sTipoCuenta_Origen, 
                    string sCuenta_Origen, 
                    string sMonto, 
                    string sDirigidoA, 
                    string sFechaAperturaCta, 
                    string sSaldoPromediom, 
                    string sMesesRef, 
                    string sCifras, 
                    string sTipoRef, 
                    string sStatus, 
                    object userState) {
            if ((this.LogRefBankAddOperationCompleted == null)) {
                this.LogRefBankAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogRefBankAddOperationCompleted);
            }
            this.InvokeAsync("LogRefBankAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sTipoCuenta_Origen,
                        sCuenta_Origen,
                        sMonto,
                        sDirigidoA,
                        sFechaAperturaCta,
                        sSaldoPromediom,
                        sMesesRef,
                        sCifras,
                        sTipoRef,
                        sStatus}, this.LogRefBankAddOperationCompleted, userState);
        }
        
        private void OnLogRefBankAddOperationCompleted(object arg) {
            if ((this.LogRefBankAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogRefBankAddCompleted(this, new LogRefBankAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogRegUsAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LogRegUsAdd(long nAF_Id, string sAF_NombreUsuario, System.DateTime Fecha_Trans, string sTime_Trans, string sAF_IP, string sCod_Trans, string sReferencia, string sConcepto) {
            object[] results = this.Invoke("LogRegUsAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sReferencia,
                        sConcepto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LogRegUsAddAsync(long nAF_Id, string sAF_NombreUsuario, System.DateTime Fecha_Trans, string sTime_Trans, string sAF_IP, string sCod_Trans, string sReferencia, string sConcepto) {
            this.LogRegUsAddAsync(nAF_Id, sAF_NombreUsuario, Fecha_Trans, sTime_Trans, sAF_IP, sCod_Trans, sReferencia, sConcepto, null);
        }
        
        /// <remarks/>
        public void LogRegUsAddAsync(long nAF_Id, string sAF_NombreUsuario, System.DateTime Fecha_Trans, string sTime_Trans, string sAF_IP, string sCod_Trans, string sReferencia, string sConcepto, object userState) {
            if ((this.LogRegUsAddOperationCompleted == null)) {
                this.LogRegUsAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogRegUsAddOperationCompleted);
            }
            this.InvokeAsync("LogRegUsAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sReferencia,
                        sConcepto}, this.LogRegUsAddOperationCompleted, userState);
        }
        
        private void OnLogRegUsAddOperationCompleted(object arg) {
            if ((this.LogRegUsAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogRegUsAddCompleted(this, new LogRegUsAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogTransAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LogTransAdd(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    System.DateTime Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sReferencia, 
                    string sCuenta_Origen, 
                    string sCuenta_Destino, 
                    string sMonto, 
                    string sBanco, 
                    string sTipo_Tarjeta, 
                    string sBeneficiario, 
                    string sCedula_Id_B, 
                    string sSerial_Chequera, 
                    string sCheques, 
                    string sTitular, 
                    int iCantidad, 
                    string sConcepto, 
                    string sMotivo_Suspension, 
                    string sDir_Envio_Chequera) {
            object[] results = this.Invoke("LogTransAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sReferencia,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto,
                        sBanco,
                        sTipo_Tarjeta,
                        sBeneficiario,
                        sCedula_Id_B,
                        sSerial_Chequera,
                        sCheques,
                        sTitular,
                        iCantidad,
                        sConcepto,
                        sMotivo_Suspension,
                        sDir_Envio_Chequera});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LogTransAddAsync(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    System.DateTime Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sReferencia, 
                    string sCuenta_Origen, 
                    string sCuenta_Destino, 
                    string sMonto, 
                    string sBanco, 
                    string sTipo_Tarjeta, 
                    string sBeneficiario, 
                    string sCedula_Id_B, 
                    string sSerial_Chequera, 
                    string sCheques, 
                    string sTitular, 
                    int iCantidad, 
                    string sConcepto, 
                    string sMotivo_Suspension, 
                    string sDir_Envio_Chequera) {
            this.LogTransAddAsync(nAF_Id, sAF_NombreUsuario, Fecha_Trans, sTime_Trans, sAF_IP, sCod_Trans, sReferencia, sCuenta_Origen, sCuenta_Destino, sMonto, sBanco, sTipo_Tarjeta, sBeneficiario, sCedula_Id_B, sSerial_Chequera, sCheques, sTitular, iCantidad, sConcepto, sMotivo_Suspension, sDir_Envio_Chequera, null);
        }
        
        /// <remarks/>
        public void LogTransAddAsync(
                    long nAF_Id, 
                    string sAF_NombreUsuario, 
                    System.DateTime Fecha_Trans, 
                    string sTime_Trans, 
                    string sAF_IP, 
                    string sCod_Trans, 
                    string sReferencia, 
                    string sCuenta_Origen, 
                    string sCuenta_Destino, 
                    string sMonto, 
                    string sBanco, 
                    string sTipo_Tarjeta, 
                    string sBeneficiario, 
                    string sCedula_Id_B, 
                    string sSerial_Chequera, 
                    string sCheques, 
                    string sTitular, 
                    int iCantidad, 
                    string sConcepto, 
                    string sMotivo_Suspension, 
                    string sDir_Envio_Chequera, 
                    object userState) {
            if ((this.LogTransAddOperationCompleted == null)) {
                this.LogTransAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogTransAddOperationCompleted);
            }
            this.InvokeAsync("LogTransAdd", new object[] {
                        nAF_Id,
                        sAF_NombreUsuario,
                        Fecha_Trans,
                        sTime_Trans,
                        sAF_IP,
                        sCod_Trans,
                        sReferencia,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto,
                        sBanco,
                        sTipo_Tarjeta,
                        sBeneficiario,
                        sCedula_Id_B,
                        sSerial_Chequera,
                        sCheques,
                        sTitular,
                        iCantidad,
                        sConcepto,
                        sMotivo_Suspension,
                        sDir_Envio_Chequera}, this.LogTransAddOperationCompleted, userState);
        }
        
        private void OnLogTransAddOperationCompleted(object arg) {
            if ((this.LogTransAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogTransAddCompleted(this, new LogTransAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BDI_TipoTransaccionGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BDI_TipoTransaccionGet() {
            object[] results = this.Invoke("BDI_TipoTransaccionGet", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionGetAsync() {
            this.BDI_TipoTransaccionGetAsync(null);
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionGetAsync(object userState) {
            if ((this.BDI_TipoTransaccionGetOperationCompleted == null)) {
                this.BDI_TipoTransaccionGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBDI_TipoTransaccionGetOperationCompleted);
            }
            this.InvokeAsync("BDI_TipoTransaccionGet", new object[0], this.BDI_TipoTransaccionGetOperationCompleted, userState);
        }
        
        private void OnBDI_TipoTransaccionGetOperationCompleted(object arg) {
            if ((this.BDI_TipoTransaccionGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BDI_TipoTransaccionGetCompleted(this, new BDI_TipoTransaccionGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BDI_TipoTransaccionLogGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BDI_TipoTransaccionLogGet(int idtipopadre) {
            object[] results = this.Invoke("BDI_TipoTransaccionLogGet", new object[] {
                        idtipopadre});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionLogGetAsync(int idtipopadre) {
            this.BDI_TipoTransaccionLogGetAsync(idtipopadre, null);
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionLogGetAsync(int idtipopadre, object userState) {
            if ((this.BDI_TipoTransaccionLogGetOperationCompleted == null)) {
                this.BDI_TipoTransaccionLogGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBDI_TipoTransaccionLogGetOperationCompleted);
            }
            this.InvokeAsync("BDI_TipoTransaccionLogGet", new object[] {
                        idtipopadre}, this.BDI_TipoTransaccionLogGetOperationCompleted, userState);
        }
        
        private void OnBDI_TipoTransaccionLogGetOperationCompleted(object arg) {
            if ((this.BDI_TipoTransaccionLogGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BDI_TipoTransaccionLogGetCompleted(this, new BDI_TipoTransaccionLogGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BDI_TipoTransaccionPadreGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BDI_TipoTransaccionPadreGet() {
            object[] results = this.Invoke("BDI_TipoTransaccionPadreGet", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionPadreGetAsync() {
            this.BDI_TipoTransaccionPadreGetAsync(null);
        }
        
        /// <remarks/>
        public void BDI_TipoTransaccionPadreGetAsync(object userState) {
            if ((this.BDI_TipoTransaccionPadreGetOperationCompleted == null)) {
                this.BDI_TipoTransaccionPadreGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBDI_TipoTransaccionPadreGetOperationCompleted);
            }
            this.InvokeAsync("BDI_TipoTransaccionPadreGet", new object[0], this.BDI_TipoTransaccionPadreGetOperationCompleted, userState);
        }
        
        private void OnBDI_TipoTransaccionPadreGetOperationCompleted(object arg) {
            if ((this.BDI_TipoTransaccionPadreGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BDI_TipoTransaccionPadreGetCompleted(this, new BDI_TipoTransaccionPadreGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogTransGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LogTransGet(TipoTransaccion tipotransaccion, long AF_Id, string Cod_Trans, System.DateTime Fecha_TransD, System.DateTime Fecha_TransH, decimal MontoD, decimal MontoH) {
            object[] results = this.Invoke("LogTransGet", new object[] {
                        tipotransaccion,
                        AF_Id,
                        Cod_Trans,
                        Fecha_TransD,
                        Fecha_TransH,
                        MontoD,
                        MontoH});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LogTransGetAsync(TipoTransaccion tipotransaccion, long AF_Id, string Cod_Trans, System.DateTime Fecha_TransD, System.DateTime Fecha_TransH, decimal MontoD, decimal MontoH) {
            this.LogTransGetAsync(tipotransaccion, AF_Id, Cod_Trans, Fecha_TransD, Fecha_TransH, MontoD, MontoH, null);
        }
        
        /// <remarks/>
        public void LogTransGetAsync(TipoTransaccion tipotransaccion, long AF_Id, string Cod_Trans, System.DateTime Fecha_TransD, System.DateTime Fecha_TransH, decimal MontoD, decimal MontoH, object userState) {
            if ((this.LogTransGetOperationCompleted == null)) {
                this.LogTransGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogTransGetOperationCompleted);
            }
            this.InvokeAsync("LogTransGet", new object[] {
                        tipotransaccion,
                        AF_Id,
                        Cod_Trans,
                        Fecha_TransD,
                        Fecha_TransH,
                        MontoD,
                        MontoH}, this.LogTransGetOperationCompleted, userState);
        }
        
        private void OnLogTransGetOperationCompleted(object arg) {
            if ((this.LogTransGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogTransGetCompleted(this, new LogTransGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogTransDiarioAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LogTransDiarioAdd(long nAF_Id, System.DateTime Fecha_Trans, string sTime_Trans, string sCod_Trans, string sReferencia, string sCuenta_Origen, string sCuenta_Destino, string sMonto) {
            object[] results = this.Invoke("LogTransDiarioAdd", new object[] {
                        nAF_Id,
                        Fecha_Trans,
                        sTime_Trans,
                        sCod_Trans,
                        sReferencia,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LogTransDiarioAddAsync(long nAF_Id, System.DateTime Fecha_Trans, string sTime_Trans, string sCod_Trans, string sReferencia, string sCuenta_Origen, string sCuenta_Destino, string sMonto) {
            this.LogTransDiarioAddAsync(nAF_Id, Fecha_Trans, sTime_Trans, sCod_Trans, sReferencia, sCuenta_Origen, sCuenta_Destino, sMonto, null);
        }
        
        /// <remarks/>
        public void LogTransDiarioAddAsync(long nAF_Id, System.DateTime Fecha_Trans, string sTime_Trans, string sCod_Trans, string sReferencia, string sCuenta_Origen, string sCuenta_Destino, string sMonto, object userState) {
            if ((this.LogTransDiarioAddOperationCompleted == null)) {
                this.LogTransDiarioAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogTransDiarioAddOperationCompleted);
            }
            this.InvokeAsync("LogTransDiarioAdd", new object[] {
                        nAF_Id,
                        Fecha_Trans,
                        sTime_Trans,
                        sCod_Trans,
                        sReferencia,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto}, this.LogTransDiarioAddOperationCompleted, userState);
        }
        
        private void OnLogTransDiarioAddOperationCompleted(object arg) {
            if ((this.LogTransDiarioAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogTransDiarioAddCompleted(this, new LogTransDiarioAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumeroOperDiarias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumeroOperDiarias(long nAF_Id, string sCuenta_Origen, string sCuenta_Destino, string sMonto) {
            object[] results = this.Invoke("GetNumeroOperDiarias", new object[] {
                        nAF_Id,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroOperDiariasAsync(long nAF_Id, string sCuenta_Origen, string sCuenta_Destino, string sMonto) {
            this.GetNumeroOperDiariasAsync(nAF_Id, sCuenta_Origen, sCuenta_Destino, sMonto, null);
        }
        
        /// <remarks/>
        public void GetNumeroOperDiariasAsync(long nAF_Id, string sCuenta_Origen, string sCuenta_Destino, string sMonto, object userState) {
            if ((this.GetNumeroOperDiariasOperationCompleted == null)) {
                this.GetNumeroOperDiariasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroOperDiariasOperationCompleted);
            }
            this.InvokeAsync("GetNumeroOperDiarias", new object[] {
                        nAF_Id,
                        sCuenta_Origen,
                        sCuenta_Destino,
                        sMonto}, this.GetNumeroOperDiariasOperationCompleted, userState);
        }
        
        private void OnGetNumeroOperDiariasOperationCompleted(object arg) {
            if ((this.GetNumeroOperDiariasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroOperDiariasCompleted(this, new GetNumeroOperDiariasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProveedoresGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProveedoresGet(long nPV_IDIn) {
            object[] results = this.Invoke("ProveedoresGet", new object[] {
                        nPV_IDIn});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ProveedoresGetAsync(long nPV_IDIn) {
            this.ProveedoresGetAsync(nPV_IDIn, null);
        }
        
        /// <remarks/>
        public void ProveedoresGetAsync(long nPV_IDIn, object userState) {
            if ((this.ProveedoresGetOperationCompleted == null)) {
                this.ProveedoresGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProveedoresGetOperationCompleted);
            }
            this.InvokeAsync("ProveedoresGet", new object[] {
                        nPV_IDIn}, this.ProveedoresGetOperationCompleted, userState);
        }
        
        private void OnProveedoresGetOperationCompleted(object arg) {
            if ((this.ProveedoresGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProveedoresGetCompleted(this, new ProveedoresGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteProducto(long id) {
            object[] results = this.Invoke("DeleteProducto", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProductoAsync(long id) {
            this.DeleteProductoAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteProductoAsync(long id, object userState) {
            if ((this.DeleteProductoOperationCompleted == null)) {
                this.DeleteProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductoOperationCompleted);
            }
            this.InvokeAsync("DeleteProducto", new object[] {
                        id}, this.DeleteProductoOperationCompleted, userState);
        }
        
        private void OnDeleteProductoOperationCompleted(object arg) {
            if ((this.DeleteProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductoCompleted(this, new DeleteProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgenciasGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AgenciasGet() {
            object[] results = this.Invoke("AgenciasGet", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AgenciasGetAsync() {
            this.AgenciasGetAsync(null);
        }
        
        /// <remarks/>
        public void AgenciasGetAsync(object userState) {
            if ((this.AgenciasGetOperationCompleted == null)) {
                this.AgenciasGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenciasGetOperationCompleted);
            }
            this.InvokeAsync("AgenciasGet", new object[0], this.AgenciasGetOperationCompleted, userState);
        }
        
        private void OnAgenciasGetOperationCompleted(object arg) {
            if ((this.AgenciasGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgenciasGetCompleted(this, new AgenciasGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgenciaGetById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AgenciaGetById(long id) {
            object[] results = this.Invoke("AgenciaGetById", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AgenciaGetByIdAsync(long id) {
            this.AgenciaGetByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void AgenciaGetByIdAsync(long id, object userState) {
            if ((this.AgenciaGetByIdOperationCompleted == null)) {
                this.AgenciaGetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenciaGetByIdOperationCompleted);
            }
            this.InvokeAsync("AgenciaGetById", new object[] {
                        id}, this.AgenciaGetByIdOperationCompleted, userState);
        }
        
        private void OnAgenciaGetByIdOperationCompleted(object arg) {
            if ((this.AgenciaGetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgenciaGetByIdCompleted(this, new AgenciaGetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TiposFind", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TiposFind(long nTI_id) {
            object[] results = this.Invoke("TiposFind", new object[] {
                        nTI_id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TiposFindAsync(long nTI_id) {
            this.TiposFindAsync(nTI_id, null);
        }
        
        /// <remarks/>
        public void TiposFindAsync(long nTI_id, object userState) {
            if ((this.TiposFindOperationCompleted == null)) {
                this.TiposFindOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTiposFindOperationCompleted);
            }
            this.InvokeAsync("TiposFind", new object[] {
                        nTI_id}, this.TiposFindOperationCompleted, userState);
        }
        
        private void OnTiposFindOperationCompleted(object arg) {
            if ((this.TiposFindCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TiposFindCompleted(this, new TiposFindCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BankGetByType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BankGetByType(bool conBFC, string tipoString) {
            object[] results = this.Invoke("BankGetByType", new object[] {
                        conBFC,
                        tipoString});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BankGetByTypeAsync(bool conBFC, string tipoString) {
            this.BankGetByTypeAsync(conBFC, tipoString, null);
        }
        
        /// <remarks/>
        public void BankGetByTypeAsync(bool conBFC, string tipoString, object userState) {
            if ((this.BankGetByTypeOperationCompleted == null)) {
                this.BankGetByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankGetByTypeOperationCompleted);
            }
            this.InvokeAsync("BankGetByType", new object[] {
                        conBFC,
                        tipoString}, this.BankGetByTypeOperationCompleted, userState);
        }
        
        private void OnBankGetByTypeOperationCompleted(object arg) {
            if ((this.BankGetByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankGetByTypeCompleted(this, new BankGetByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BankGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BankGet(bool conBFC) {
            object[] results = this.Invoke("BankGet", new object[] {
                        conBFC});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BankGetAsync(bool conBFC) {
            this.BankGetAsync(conBFC, null);
        }
        
        /// <remarks/>
        public void BankGetAsync(bool conBFC, object userState) {
            if ((this.BankGetOperationCompleted == null)) {
                this.BankGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankGetOperationCompleted);
            }
            this.InvokeAsync("BankGet", new object[] {
                        conBFC}, this.BankGetOperationCompleted, userState);
        }
        
        private void OnBankGetOperationCompleted(object arg) {
            if ((this.BankGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankGetCompleted(this, new BankGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BankGetById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BankGetById(string id) {
            object[] results = this.Invoke("BankGetById", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BankGetByIdAsync(string id) {
            this.BankGetByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void BankGetByIdAsync(string id, object userState) {
            if ((this.BankGetByIdOperationCompleted == null)) {
                this.BankGetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankGetByIdOperationCompleted);
            }
            this.InvokeAsync("BankGetById", new object[] {
                        id}, this.BankGetByIdOperationCompleted, userState);
        }
        
        private void OnBankGetByIdOperationCompleted(object arg) {
            if ((this.BankGetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankGetByIdCompleted(this, new BankGetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BankGetByBin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BankGetByBin(string strBinId) {
            object[] results = this.Invoke("BankGetByBin", new object[] {
                        strBinId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BankGetByBinAsync(string strBinId) {
            this.BankGetByBinAsync(strBinId, null);
        }
        
        /// <remarks/>
        public void BankGetByBinAsync(string strBinId, object userState) {
            if ((this.BankGetByBinOperationCompleted == null)) {
                this.BankGetByBinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankGetByBinOperationCompleted);
            }
            this.InvokeAsync("BankGetByBin", new object[] {
                        strBinId}, this.BankGetByBinOperationCompleted, userState);
        }
        
        private void OnBankGetByBinOperationCompleted(object arg) {
            if ((this.BankGetByBinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankGetByBinCompleted(this, new BankGetByBinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumeroReferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetNumeroReferencia() {
            object[] results = this.Invoke("GetNumeroReferencia", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroReferenciaAsync() {
            this.GetNumeroReferenciaAsync(null);
        }
        
        /// <remarks/>
        public void GetNumeroReferenciaAsync(object userState) {
            if ((this.GetNumeroReferenciaOperationCompleted == null)) {
                this.GetNumeroReferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroReferenciaOperationCompleted);
            }
            this.InvokeAsync("GetNumeroReferencia", new object[0], this.GetNumeroReferenciaOperationCompleted, userState);
        }
        
        private void OnGetNumeroReferenciaOperationCompleted(object arg) {
            if ((this.GetNumeroReferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroReferenciaCompleted(this, new GetNumeroReferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumeroReferenciaCrediCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetNumeroReferenciaCrediCard() {
            object[] results = this.Invoke("GetNumeroReferenciaCrediCard", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroReferenciaCrediCardAsync() {
            this.GetNumeroReferenciaCrediCardAsync(null);
        }
        
        /// <remarks/>
        public void GetNumeroReferenciaCrediCardAsync(object userState) {
            if ((this.GetNumeroReferenciaCrediCardOperationCompleted == null)) {
                this.GetNumeroReferenciaCrediCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroReferenciaCrediCardOperationCompleted);
            }
            this.InvokeAsync("GetNumeroReferenciaCrediCard", new object[0], this.GetNumeroReferenciaCrediCardOperationCompleted, userState);
        }
        
        private void OnGetNumeroReferenciaCrediCardOperationCompleted(object arg) {
            if ((this.GetNumeroReferenciaCrediCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroReferenciaCrediCardCompleted(this, new GetNumeroReferenciaCrediCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkBineCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ChkBineCard(string sBink_ID, string sBankID, string sBinStatu) {
            object[] results = this.Invoke("ChkBineCard", new object[] {
                        sBink_ID,
                        sBankID,
                        sBinStatu});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ChkBineCardAsync(string sBink_ID, string sBankID, string sBinStatu) {
            this.ChkBineCardAsync(sBink_ID, sBankID, sBinStatu, null);
        }
        
        /// <remarks/>
        public void ChkBineCardAsync(string sBink_ID, string sBankID, string sBinStatu, object userState) {
            if ((this.ChkBineCardOperationCompleted == null)) {
                this.ChkBineCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChkBineCardOperationCompleted);
            }
            this.InvokeAsync("ChkBineCard", new object[] {
                        sBink_ID,
                        sBankID,
                        sBinStatu}, this.ChkBineCardOperationCompleted, userState);
        }
        
        private void OnChkBineCardOperationCompleted(object arg) {
            if ((this.ChkBineCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChkBineCardCompleted(this, new ChkBineCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTipoTarjetas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTipoTarjetas(string nStatu) {
            object[] results = this.Invoke("GetTipoTarjetas", new object[] {
                        nStatu});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTipoTarjetasAsync(string nStatu) {
            this.GetTipoTarjetasAsync(nStatu, null);
        }
        
        /// <remarks/>
        public void GetTipoTarjetasAsync(string nStatu, object userState) {
            if ((this.GetTipoTarjetasOperationCompleted == null)) {
                this.GetTipoTarjetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTipoTarjetasOperationCompleted);
            }
            this.InvokeAsync("GetTipoTarjetas", new object[] {
                        nStatu}, this.GetTipoTarjetasOperationCompleted, userState);
        }
        
        private void OnGetTipoTarjetasOperationCompleted(object arg) {
            if ((this.GetTipoTarjetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTipoTarjetasCompleted(this, new GetTipoTarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BDI_DatosCorreoGetByDC_CodTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BDI_DatosCorreoGetByDC_CodTrans(string codtrans) {
            object[] results = this.Invoke("BDI_DatosCorreoGetByDC_CodTrans", new object[] {
                        codtrans});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BDI_DatosCorreoGetByDC_CodTransAsync(string codtrans) {
            this.BDI_DatosCorreoGetByDC_CodTransAsync(codtrans, null);
        }
        
        /// <remarks/>
        public void BDI_DatosCorreoGetByDC_CodTransAsync(string codtrans, object userState) {
            if ((this.BDI_DatosCorreoGetByDC_CodTransOperationCompleted == null)) {
                this.BDI_DatosCorreoGetByDC_CodTransOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBDI_DatosCorreoGetByDC_CodTransOperationCompleted);
            }
            this.InvokeAsync("BDI_DatosCorreoGetByDC_CodTrans", new object[] {
                        codtrans}, this.BDI_DatosCorreoGetByDC_CodTransOperationCompleted, userState);
        }
        
        private void OnBDI_DatosCorreoGetByDC_CodTransOperationCompleted(object arg) {
            if ((this.BDI_DatosCorreoGetByDC_CodTransCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BDI_DatosCorreoGetByDC_CodTransCompleted(this, new BDI_DatosCorreoGetByDC_CodTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DiasPasswordget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DiasPasswordget() {
            object[] results = this.Invoke("DiasPasswordget", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DiasPasswordgetAsync() {
            this.DiasPasswordgetAsync(null);
        }
        
        /// <remarks/>
        public void DiasPasswordgetAsync(object userState) {
            if ((this.DiasPasswordgetOperationCompleted == null)) {
                this.DiasPasswordgetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDiasPasswordgetOperationCompleted);
            }
            this.InvokeAsync("DiasPasswordget", new object[0], this.DiasPasswordgetOperationCompleted, userState);
        }
        
        private void OnDiasPasswordgetOperationCompleted(object arg) {
            if ((this.DiasPasswordgetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DiasPasswordgetCompleted(this, new DiasPasswordgetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveSendMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveSendMsg(string msg, string destiny, Origen origen, string codigoRetorno, string descripcionRetorno) {
            this.Invoke("SaveSendMsg", new object[] {
                        msg,
                        destiny,
                        origen,
                        codigoRetorno,
                        descripcionRetorno});
        }
        
        /// <remarks/>
        public void SaveSendMsgAsync(string msg, string destiny, Origen origen, string codigoRetorno, string descripcionRetorno) {
            this.SaveSendMsgAsync(msg, destiny, origen, codigoRetorno, descripcionRetorno, null);
        }
        
        /// <remarks/>
        public void SaveSendMsgAsync(string msg, string destiny, Origen origen, string codigoRetorno, string descripcionRetorno, object userState) {
            if ((this.SaveSendMsgOperationCompleted == null)) {
                this.SaveSendMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSendMsgOperationCompleted);
            }
            this.InvokeAsync("SaveSendMsg", new object[] {
                        msg,
                        destiny,
                        origen,
                        codigoRetorno,
                        descripcionRetorno}, this.SaveSendMsgOperationCompleted, userState);
        }
        
        private void OnSaveSendMsgOperationCompleted(object arg) {
            if ((this.SaveSendMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSendMsgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoTransaccion {
        
        /// <comentarios/>
        DelDia,
        
        /// <comentarios/>
        DelDiaAnterior,
        
        /// <comentarios/>
        DelMes,
        
        /// <comentarios/>
        DelMesAnterior,
        
        /// <comentarios/>
        PorRango,
        
        /// <comentarios/>
        Ultimos20,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Origen {
        
        /// <comentarios/>
        NATURAL,
        
        /// <comentarios/>
        JURIDICO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EstatusGetCompletedEventHandler(object sender, EstatusGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstatusGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstatusGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Def_LovGetCompletedEventHandler(object sender, Def_LovGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Def_LovGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Def_LovGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogRefBankAddCompletedEventHandler(object sender, LogRefBankAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogRefBankAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogRefBankAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogRegUsAddCompletedEventHandler(object sender, LogRegUsAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogRegUsAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogRegUsAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogTransAddCompletedEventHandler(object sender, LogTransAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogTransAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogTransAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BDI_TipoTransaccionGetCompletedEventHandler(object sender, BDI_TipoTransaccionGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDI_TipoTransaccionGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BDI_TipoTransaccionGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BDI_TipoTransaccionLogGetCompletedEventHandler(object sender, BDI_TipoTransaccionLogGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDI_TipoTransaccionLogGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BDI_TipoTransaccionLogGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BDI_TipoTransaccionPadreGetCompletedEventHandler(object sender, BDI_TipoTransaccionPadreGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDI_TipoTransaccionPadreGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BDI_TipoTransaccionPadreGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogTransGetCompletedEventHandler(object sender, LogTransGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogTransGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogTransGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogTransDiarioAddCompletedEventHandler(object sender, LogTransDiarioAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogTransDiarioAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogTransDiarioAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetNumeroOperDiariasCompletedEventHandler(object sender, GetNumeroOperDiariasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroOperDiariasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroOperDiariasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ProveedoresGetCompletedEventHandler(object sender, ProveedoresGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProveedoresGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProveedoresGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DeleteProductoCompletedEventHandler(object sender, DeleteProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AgenciasGetCompletedEventHandler(object sender, AgenciasGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgenciasGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgenciasGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AgenciaGetByIdCompletedEventHandler(object sender, AgenciaGetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgenciaGetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgenciaGetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TiposFindCompletedEventHandler(object sender, TiposFindCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TiposFindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TiposFindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BankGetByTypeCompletedEventHandler(object sender, BankGetByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankGetByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankGetByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BankGetCompletedEventHandler(object sender, BankGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BankGetByIdCompletedEventHandler(object sender, BankGetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankGetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankGetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BankGetByBinCompletedEventHandler(object sender, BankGetByBinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankGetByBinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankGetByBinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetNumeroReferenciaCompletedEventHandler(object sender, GetNumeroReferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroReferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroReferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetNumeroReferenciaCrediCardCompletedEventHandler(object sender, GetNumeroReferenciaCrediCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroReferenciaCrediCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroReferenciaCrediCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ChkBineCardCompletedEventHandler(object sender, ChkBineCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChkBineCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChkBineCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetTipoTarjetasCompletedEventHandler(object sender, GetTipoTarjetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTipoTarjetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTipoTarjetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BDI_DatosCorreoGetByDC_CodTransCompletedEventHandler(object sender, BDI_DatosCorreoGetByDC_CodTransCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDI_DatosCorreoGetByDC_CodTransCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BDI_DatosCorreoGetByDC_CodTransCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DiasPasswordgetCompletedEventHandler(object sender, DiasPasswordgetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DiasPasswordgetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DiasPasswordgetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SaveSendMsgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591