//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBBAV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.18.52.162:8080/bavWebSrvIbs/services/IbsService")]
        public string IBBAV_WsIbsService_IbsService {
            get {
                return ((string)(this["IBBAV_WsIbsService_IbsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8080/bavWebSrvIbs/services/IbsService")]
        public string IBBAV_WsIbsService_IbsServiceService {
            get {
                return ((string)(this["IBBAV_WsIbsService_IbsServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8084/WsNotif_IBP.asmx.asmx")]
        public string IBBAV_WsNotif_IBP_WsNotif_IBP_asmx {
            get {
                return ((string)(this["IBBAV_WsNotif_IBP_WsNotif_IBP_asmx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://200.41.57.109:8086/m4.in.wsint/services/M4WSIntSR.M4WSIntSRHttpSoap11Endpo" +
            "int/")]
        public string IBBAV_WSTedexis_M4WSIntSR {
            get {
                return ((string)(this["IBBAV_WSTedexis_M4WSIntSR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsMenu.asmx")]
        public string IBBAV_WsMenu_WsMenu {
            get {
                return ((string)(this["IBBAV_WsMenu_WsMenu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsSession.asmx")]
        public string IBBAV_WsSession_WsSession {
            get {
                return ((string)(this["IBBAV_WsSession_WsSession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsErrores.asmx")]
        public string IBBAV_WsErrores_WsErrores {
            get {
                return ((string)(this["IBBAV_WsErrores_WsErrores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsLogons.asmx")]
        public string IBBAV_WsLogons_WsLogons {
            get {
                return ((string)(this["IBBAV_WsLogons_WsLogons"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsGlobal.asmx")]
        public string IBBAV_WsGlobal_WsGlobal {
            get {
                return ((string)(this["IBBAV_WsGlobal_WsGlobal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsFavoritos.asmx")]
        public string IBBAV_WsFavoritos_WsFavoritos {
            get {
                return ((string)(this["IBBAV_WsFavoritos_WsFavoritos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsServicios.asmx")]
        public string IBBAV_WsServicios_WsServicios {
            get {
                return ((string)(this["IBBAV_WsServicios_WsServicios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsTransaccion.asmx")]
        public string IBBAV_WsTransaccion_WsTransaccion {
            get {
                return ((string)(this["IBBAV_WsTransaccion_WsTransaccion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8083/Service.asmx")]
        public string IBBAV_WsMensajeria_Service {
            get {
                return ((string)(this["IBBAV_WsMensajeria_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8080/Adelanto_Credito_SOAP/services/ExtraCredito")]
        public string IBBAV_WsExtraefectivo_ExtraCreditoService {
            get {
                return ((string)(this["IBBAV_WsExtraefectivo_ExtraCreditoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.19.52.230:8082/WsAfiliados.asmx")]
        public string IBBAV_WsAfiliados_WsAfiliados {
            get {
                return ((string)(this["IBBAV_WsAfiliados_WsAfiliados"]));
            }
        }
    }
}
