//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsLogons {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsLogonsSoap", Namespace="http://tempuri.org/")]
    public partial class WsLogons : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PasswordUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback IntentosValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarAfiliacionIntentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberFailedLogonOperationCompleted;
        
        private System.Threading.SendOrPostCallback BloquearAccesoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsLogons() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsLogons_WsLogons;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PasswordUpdateCompletedEventHandler PasswordUpdateCompleted;
        
        /// <remarks/>
        public event IntentosValidateCompletedEventHandler IntentosValidateCompleted;
        
        /// <remarks/>
        public event ValidarAfiliacionIntentosCompletedEventHandler ValidarAfiliacionIntentosCompleted;
        
        /// <remarks/>
        public event GetNumberFailedLogonCompletedEventHandler GetNumberFailedLogonCompleted;
        
        /// <remarks/>
        public event BloquearAccesoCompletedEventHandler BloquearAccesoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PasswordUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PasswordUpdate(long AF_Id, string AF_PasswordOld, string AF_PasswordNew, int AF_DiasPassword, string FI_IP, string TI_Nemotecnico, int sCod) {
            object[] results = this.Invoke("PasswordUpdate", new object[] {
                        AF_Id,
                        AF_PasswordOld,
                        AF_PasswordNew,
                        AF_DiasPassword,
                        FI_IP,
                        TI_Nemotecnico,
                        sCod});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PasswordUpdateAsync(long AF_Id, string AF_PasswordOld, string AF_PasswordNew, int AF_DiasPassword, string FI_IP, string TI_Nemotecnico, int sCod) {
            this.PasswordUpdateAsync(AF_Id, AF_PasswordOld, AF_PasswordNew, AF_DiasPassword, FI_IP, TI_Nemotecnico, sCod, null);
        }
        
        /// <remarks/>
        public void PasswordUpdateAsync(long AF_Id, string AF_PasswordOld, string AF_PasswordNew, int AF_DiasPassword, string FI_IP, string TI_Nemotecnico, int sCod, object userState) {
            if ((this.PasswordUpdateOperationCompleted == null)) {
                this.PasswordUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPasswordUpdateOperationCompleted);
            }
            this.InvokeAsync("PasswordUpdate", new object[] {
                        AF_Id,
                        AF_PasswordOld,
                        AF_PasswordNew,
                        AF_DiasPassword,
                        FI_IP,
                        TI_Nemotecnico,
                        sCod}, this.PasswordUpdateOperationCompleted, userState);
        }
        
        private void OnPasswordUpdateOperationCompleted(object arg) {
            if ((this.PasswordUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PasswordUpdateCompleted(this, new PasswordUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IntentosValidate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet IntentosValidate(long AF_Id, string AF_Password, string AF_RespuestaPD, string FI_IP, string TI_Nemotecnico, int sCod) {
            object[] results = this.Invoke("IntentosValidate", new object[] {
                        AF_Id,
                        AF_Password,
                        AF_RespuestaPD,
                        FI_IP,
                        TI_Nemotecnico,
                        sCod});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void IntentosValidateAsync(long AF_Id, string AF_Password, string AF_RespuestaPD, string FI_IP, string TI_Nemotecnico, int sCod) {
            this.IntentosValidateAsync(AF_Id, AF_Password, AF_RespuestaPD, FI_IP, TI_Nemotecnico, sCod, null);
        }
        
        /// <remarks/>
        public void IntentosValidateAsync(long AF_Id, string AF_Password, string AF_RespuestaPD, string FI_IP, string TI_Nemotecnico, int sCod, object userState) {
            if ((this.IntentosValidateOperationCompleted == null)) {
                this.IntentosValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntentosValidateOperationCompleted);
            }
            this.InvokeAsync("IntentosValidate", new object[] {
                        AF_Id,
                        AF_Password,
                        AF_RespuestaPD,
                        FI_IP,
                        TI_Nemotecnico,
                        sCod}, this.IntentosValidateOperationCompleted, userState);
        }
        
        private void OnIntentosValidateOperationCompleted(object arg) {
            if ((this.IntentosValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntentosValidateCompleted(this, new IntentosValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarAfiliacionIntentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarAfiliacionIntentos(string tarjeta, string clave, string tipo) {
            object[] results = this.Invoke("ValidarAfiliacionIntentos", new object[] {
                        tarjeta,
                        clave,
                        tipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarAfiliacionIntentosAsync(string tarjeta, string clave, string tipo) {
            this.ValidarAfiliacionIntentosAsync(tarjeta, clave, tipo, null);
        }
        
        /// <remarks/>
        public void ValidarAfiliacionIntentosAsync(string tarjeta, string clave, string tipo, object userState) {
            if ((this.ValidarAfiliacionIntentosOperationCompleted == null)) {
                this.ValidarAfiliacionIntentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarAfiliacionIntentosOperationCompleted);
            }
            this.InvokeAsync("ValidarAfiliacionIntentos", new object[] {
                        tarjeta,
                        clave,
                        tipo}, this.ValidarAfiliacionIntentosOperationCompleted, userState);
        }
        
        private void OnValidarAfiliacionIntentosOperationCompleted(object arg) {
            if ((this.ValidarAfiliacionIntentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarAfiliacionIntentosCompleted(this, new ValidarAfiliacionIntentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberFailedLogon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumberFailedLogon(string strTarjeta) {
            object[] results = this.Invoke("GetNumberFailedLogon", new object[] {
                        strTarjeta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberFailedLogonAsync(string strTarjeta) {
            this.GetNumberFailedLogonAsync(strTarjeta, null);
        }
        
        /// <remarks/>
        public void GetNumberFailedLogonAsync(string strTarjeta, object userState) {
            if ((this.GetNumberFailedLogonOperationCompleted == null)) {
                this.GetNumberFailedLogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberFailedLogonOperationCompleted);
            }
            this.InvokeAsync("GetNumberFailedLogon", new object[] {
                        strTarjeta}, this.GetNumberFailedLogonOperationCompleted, userState);
        }
        
        private void OnGetNumberFailedLogonOperationCompleted(object arg) {
            if ((this.GetNumberFailedLogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberFailedLogonCompleted(this, new GetNumberFailedLogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BloquearAcceso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BloquearAcceso(string strTarjeta) {
            object[] results = this.Invoke("BloquearAcceso", new object[] {
                        strTarjeta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BloquearAccesoAsync(string strTarjeta) {
            this.BloquearAccesoAsync(strTarjeta, null);
        }
        
        /// <remarks/>
        public void BloquearAccesoAsync(string strTarjeta, object userState) {
            if ((this.BloquearAccesoOperationCompleted == null)) {
                this.BloquearAccesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBloquearAccesoOperationCompleted);
            }
            this.InvokeAsync("BloquearAcceso", new object[] {
                        strTarjeta}, this.BloquearAccesoOperationCompleted, userState);
        }
        
        private void OnBloquearAccesoOperationCompleted(object arg) {
            if ((this.BloquearAccesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BloquearAccesoCompleted(this, new BloquearAccesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void PasswordUpdateCompletedEventHandler(object sender, PasswordUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PasswordUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PasswordUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void IntentosValidateCompletedEventHandler(object sender, IntentosValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntentosValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IntentosValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ValidarAfiliacionIntentosCompletedEventHandler(object sender, ValidarAfiliacionIntentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarAfiliacionIntentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarAfiliacionIntentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetNumberFailedLogonCompletedEventHandler(object sender, GetNumberFailedLogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberFailedLogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberFailedLogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BloquearAccesoCompletedEventHandler(object sender, BloquearAccesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BloquearAccesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BloquearAccesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591