//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsExtraefectivo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExtraCreditoSoapBinding", Namespace="http://com")]
    public partial class ExtraCreditoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback tarjetasL2OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaL2OperationCompleted;
        
        private System.Threading.SendOrPostCallback aprobacionL2OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaTarjetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCuotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback aprobacionPagoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExtraCreditoService() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsExtraefectivo_ExtraCreditoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event tarjetasL2CompletedEventHandler tarjetasL2Completed;
        
        /// <remarks/>
        public event consultaL2CompletedEventHandler consultaL2Completed;
        
        /// <remarks/>
        public event aprobacionL2CompletedEventHandler aprobacionL2Completed;
        
        /// <remarks/>
        public event consultaTarjetasCompletedEventHandler consultaTarjetasCompleted;
        
        /// <remarks/>
        public event consultarCuotasCompletedEventHandler consultarCuotasCompleted;
        
        /// <remarks/>
        public event aprobacionPagoCompletedEventHandler aprobacionPagoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tarjetasL2Return")]
        public Tarjeta[] tarjetasL2(string cedula) {
            object[] results = this.Invoke("tarjetasL2", new object[] {
                        cedula});
            return ((Tarjeta[])(results[0]));
        }
        
        /// <remarks/>
        public void tarjetasL2Async(string cedula) {
            this.tarjetasL2Async(cedula, null);
        }
        
        /// <remarks/>
        public void tarjetasL2Async(string cedula, object userState) {
            if ((this.tarjetasL2OperationCompleted == null)) {
                this.tarjetasL2OperationCompleted = new System.Threading.SendOrPostCallback(this.OntarjetasL2OperationCompleted);
            }
            this.InvokeAsync("tarjetasL2", new object[] {
                        cedula}, this.tarjetasL2OperationCompleted, userState);
        }
        
        private void OntarjetasL2OperationCompleted(object arg) {
            if ((this.tarjetasL2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tarjetasL2Completed(this, new tarjetasL2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaL2Return")]
        public Solicitud consultaL2(string cedula, string cuenta, string tarjeta, string monto) {
            object[] results = this.Invoke("consultaL2", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto});
            return ((Solicitud)(results[0]));
        }
        
        /// <remarks/>
        public void consultaL2Async(string cedula, string cuenta, string tarjeta, string monto) {
            this.consultaL2Async(cedula, cuenta, tarjeta, monto, null);
        }
        
        /// <remarks/>
        public void consultaL2Async(string cedula, string cuenta, string tarjeta, string monto, object userState) {
            if ((this.consultaL2OperationCompleted == null)) {
                this.consultaL2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaL2OperationCompleted);
            }
            this.InvokeAsync("consultaL2", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto}, this.consultaL2OperationCompleted, userState);
        }
        
        private void OnconsultaL2OperationCompleted(object arg) {
            if ((this.consultaL2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaL2Completed(this, new consultaL2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("aprobacionL2Return")]
        public Solicitud aprobacionL2(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas) {
            object[] results = this.Invoke("aprobacionL2", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto,
                        cuotas,
                        montoCuotas});
            return ((Solicitud)(results[0]));
        }
        
        /// <remarks/>
        public void aprobacionL2Async(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas) {
            this.aprobacionL2Async(cedula, cuenta, tarjeta, monto, cuotas, montoCuotas, null);
        }
        
        /// <remarks/>
        public void aprobacionL2Async(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas, object userState) {
            if ((this.aprobacionL2OperationCompleted == null)) {
                this.aprobacionL2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaprobacionL2OperationCompleted);
            }
            this.InvokeAsync("aprobacionL2", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto,
                        cuotas,
                        montoCuotas}, this.aprobacionL2OperationCompleted, userState);
        }
        
        private void OnaprobacionL2OperationCompleted(object arg) {
            if ((this.aprobacionL2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aprobacionL2Completed(this, new aprobacionL2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaTarjetasReturn")]
        public string[] consultaTarjetas(string cedula) {
            object[] results = this.Invoke("consultaTarjetas", new object[] {
                        cedula});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaTarjetasAsync(string cedula) {
            this.consultaTarjetasAsync(cedula, null);
        }
        
        /// <remarks/>
        public void consultaTarjetasAsync(string cedula, object userState) {
            if ((this.consultaTarjetasOperationCompleted == null)) {
                this.consultaTarjetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaTarjetasOperationCompleted);
            }
            this.InvokeAsync("consultaTarjetas", new object[] {
                        cedula}, this.consultaTarjetasOperationCompleted, userState);
        }
        
        private void OnconsultaTarjetasOperationCompleted(object arg) {
            if ((this.consultaTarjetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaTarjetasCompleted(this, new consultaTarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarCuotasReturn")]
        public string consultarCuotas(string cedula, string cuenta, string tarjeta, string monto) {
            object[] results = this.Invoke("consultarCuotas", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCuotasAsync(string cedula, string cuenta, string tarjeta, string monto) {
            this.consultarCuotasAsync(cedula, cuenta, tarjeta, monto, null);
        }
        
        /// <remarks/>
        public void consultarCuotasAsync(string cedula, string cuenta, string tarjeta, string monto, object userState) {
            if ((this.consultarCuotasOperationCompleted == null)) {
                this.consultarCuotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCuotasOperationCompleted);
            }
            this.InvokeAsync("consultarCuotas", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto}, this.consultarCuotasOperationCompleted, userState);
        }
        
        private void OnconsultarCuotasOperationCompleted(object arg) {
            if ((this.consultarCuotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCuotasCompleted(this, new consultarCuotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com", ResponseNamespace="http://com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("aprobacionPagoReturn")]
        public string aprobacionPago(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas) {
            object[] results = this.Invoke("aprobacionPago", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto,
                        cuotas,
                        montoCuotas});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aprobacionPagoAsync(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas) {
            this.aprobacionPagoAsync(cedula, cuenta, tarjeta, monto, cuotas, montoCuotas, null);
        }
        
        /// <remarks/>
        public void aprobacionPagoAsync(string cedula, string cuenta, string tarjeta, string monto, string cuotas, string montoCuotas, object userState) {
            if ((this.aprobacionPagoOperationCompleted == null)) {
                this.aprobacionPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaprobacionPagoOperationCompleted);
            }
            this.InvokeAsync("aprobacionPago", new object[] {
                        cedula,
                        cuenta,
                        tarjeta,
                        monto,
                        cuotas,
                        montoCuotas}, this.aprobacionPagoOperationCompleted, userState);
        }
        
        private void OnaprobacionPagoOperationCompleted(object arg) {
            if ((this.aprobacionPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aprobacionPagoCompleted(this, new aprobacionPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datos")]
    public partial class Tarjeta {
        
        private string codRespuestaField;
        
        private string descRespuestaField;
        
        private string disponibleField;
        
        private string marcaField;
        
        private string numeroField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRespuesta {
            get {
                return this.descRespuestaField;
            }
            set {
                this.descRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datos")]
    public partial class Solicitud {
        
        private string codRespuestaField;
        
        private string cuotasField;
        
        private string descRespuetaField;
        
        private string[] montoCuotaField;
        
        private string montoSolicitadoField;
        
        private string numeroCuentaField;
        
        private string numeroTarjetaField;
        
        private string referenciaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cuotas {
            get {
                return this.cuotasField;
            }
            set {
                this.cuotasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRespueta {
            get {
                return this.descRespuetaField;
            }
            set {
                this.descRespuetaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://com", IsNullable=false)]
        public string[] montoCuota {
            get {
                return this.montoCuotaField;
            }
            set {
                this.montoCuotaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string montoSolicitado {
            get {
                return this.montoSolicitadoField;
            }
            set {
                this.montoSolicitadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void tarjetasL2CompletedEventHandler(object sender, tarjetasL2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tarjetasL2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tarjetasL2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tarjeta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tarjeta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void consultaL2CompletedEventHandler(object sender, consultaL2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaL2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaL2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Solicitud Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Solicitud)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void aprobacionL2CompletedEventHandler(object sender, aprobacionL2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aprobacionL2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aprobacionL2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Solicitud Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Solicitud)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void consultaTarjetasCompletedEventHandler(object sender, consultaTarjetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaTarjetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaTarjetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void consultarCuotasCompletedEventHandler(object sender, consultarCuotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCuotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCuotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void aprobacionPagoCompletedEventHandler(object sender, aprobacionPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aprobacionPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aprobacionPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591