//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBBAV.WSTedexis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://core.ws.m4.tedexis.com", ConfigurationName="WSTedexis.M4WSIntSRPortType")]
    public interface M4WSIntSRPortType {
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMSappID", ReplyAction="urn:sendSMSappIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSappIDResponse sendSMSappID(IBBAV.WSTedexis.sendSMSappIDRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:responseSMS", ReplyAction="urn:responseSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.responseSMSResponse responseSMS(IBBAV.WSTedexis.responseSMSRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMSccappID", ReplyAction="urn:sendSMSccappIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSccappIDResponse sendSMSccappID(IBBAV.WSTedexis.sendSMSccappIDRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMSWithID", ReplyAction="urn:sendSMSWithIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSWithIDResponse sendSMSWithID(IBBAV.WSTedexis.sendSMSWithIDRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:responseSMScc", ReplyAction="urn:responseSMSccResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.responseSMSccResponse responseSMScc(IBBAV.WSTedexis.responseSMSccRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMScc", ReplyAction="urn:sendSMSccResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSccResponse sendSMScc(IBBAV.WSTedexis.sendSMSccRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMSWithIDcc", ReplyAction="urn:sendSMSWithIDccResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSWithIDccResponse sendSMSWithIDcc(IBBAV.WSTedexis.sendSMSWithIDccRequest request);
        
        // CODEGEN: El parámetro 'passport' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sendSMS", ReplyAction="urn:sendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IBBAV.WSTedexis.sendSMSResponse sendSMS(IBBAV.WSTedexis.sendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSappID", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSappIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appID;
        
        public sendSMSappIDRequest() {
        }
        
        public sendSMSappIDRequest(string passport, string password, string number, string text, string appID) {
            this.passport = passport;
            this.password = password;
            this.number = number;
            this.text = text;
            this.appID = appID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSappIDResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSappIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSappIDResponse() {
        }
        
        public sendSMSappIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responseSMS", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class responseSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string messageID;
        
        public responseSMSRequest() {
        }
        
        public responseSMSRequest(string passport, string password, string number, string text, string messageID) {
            this.passport = passport;
            this.password = password;
            this.number = number;
            this.text = text;
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responseSMSResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class responseSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public responseSMSResponse() {
        }
        
        public responseSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSccappID", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSccappIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appID;
        
        public sendSMSccappIDRequest() {
        }
        
        public sendSMSccappIDRequest(string passport, string password, string countryCode, string number, string text, string appID) {
            this.passport = passport;
            this.password = password;
            this.countryCode = countryCode;
            this.number = number;
            this.text = text;
            this.appID = appID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSccappIDResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSccappIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSccappIDResponse() {
        }
        
        public sendSMSccappIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSWithID", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSWithIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        public sendSMSWithIDRequest() {
        }
        
        public sendSMSWithIDRequest(string passport, string password, string number, string text) {
            this.passport = passport;
            this.password = password;
            this.number = number;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSWithIDResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSWithIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSWithIDResponse() {
        }
        
        public sendSMSWithIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responseSMScc", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class responseSMSccRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string messageID;
        
        public responseSMSccRequest() {
        }
        
        public responseSMSccRequest(string passport, string password, string countryCode, string number, string text, string messageID) {
            this.passport = passport;
            this.password = password;
            this.countryCode = countryCode;
            this.number = number;
            this.text = text;
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="responseSMSccResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class responseSMSccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public responseSMSccResponse() {
        }
        
        public responseSMSccResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMScc", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSccRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        public sendSMSccRequest() {
        }
        
        public sendSMSccRequest(string passport, string password, string countryCode, string number, string text) {
            this.passport = passport;
            this.password = password;
            this.countryCode = countryCode;
            this.number = number;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSccResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSccResponse() {
        }
        
        public sendSMSccResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSWithIDcc", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSWithIDccRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        public sendSMSWithIDccRequest() {
        }
        
        public sendSMSWithIDccRequest(string passport, string password, string countryCode, string number, string text) {
            this.passport = passport;
            this.password = password;
            this.countryCode = countryCode;
            this.number = number;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSWithIDccResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSWithIDccResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSWithIDccResponse() {
        }
        
        public sendSMSWithIDccResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string passport, string password, string number, string text) {
            this.passport = passport;
            this.password = password;
            this.number = number;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://core.ws.m4.tedexis.com", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://core.ws.m4.tedexis.com", Order=0)]
        public int @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface M4WSIntSRPortTypeChannel : IBBAV.WSTedexis.M4WSIntSRPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class M4WSIntSRPortTypeClient : System.ServiceModel.ClientBase<IBBAV.WSTedexis.M4WSIntSRPortType>, IBBAV.WSTedexis.M4WSIntSRPortType {
        
        public M4WSIntSRPortTypeClient() {
        }
        
        public M4WSIntSRPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public M4WSIntSRPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public M4WSIntSRPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public M4WSIntSRPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSappIDResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMSappID(IBBAV.WSTedexis.sendSMSappIDRequest request) {
            return base.Channel.sendSMSappID(request);
        }
        
        public int sendSMSappID(string passport, string password, string number, string text, string appID) {
            IBBAV.WSTedexis.sendSMSappIDRequest inValue = new IBBAV.WSTedexis.sendSMSappIDRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.number = number;
            inValue.text = text;
            inValue.appID = appID;
            IBBAV.WSTedexis.sendSMSappIDResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMSappID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.responseSMSResponse IBBAV.WSTedexis.M4WSIntSRPortType.responseSMS(IBBAV.WSTedexis.responseSMSRequest request) {
            return base.Channel.responseSMS(request);
        }
        
        public int responseSMS(string passport, string password, string number, string text, string messageID) {
            IBBAV.WSTedexis.responseSMSRequest inValue = new IBBAV.WSTedexis.responseSMSRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.number = number;
            inValue.text = text;
            inValue.messageID = messageID;
            IBBAV.WSTedexis.responseSMSResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).responseSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSccappIDResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMSccappID(IBBAV.WSTedexis.sendSMSccappIDRequest request) {
            return base.Channel.sendSMSccappID(request);
        }
        
        public int sendSMSccappID(string passport, string password, string countryCode, string number, string text, string appID) {
            IBBAV.WSTedexis.sendSMSccappIDRequest inValue = new IBBAV.WSTedexis.sendSMSccappIDRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.countryCode = countryCode;
            inValue.number = number;
            inValue.text = text;
            inValue.appID = appID;
            IBBAV.WSTedexis.sendSMSccappIDResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMSccappID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSWithIDResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMSWithID(IBBAV.WSTedexis.sendSMSWithIDRequest request) {
            return base.Channel.sendSMSWithID(request);
        }
        
        public int sendSMSWithID(string passport, string password, string number, string text) {
            IBBAV.WSTedexis.sendSMSWithIDRequest inValue = new IBBAV.WSTedexis.sendSMSWithIDRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.number = number;
            inValue.text = text;
            IBBAV.WSTedexis.sendSMSWithIDResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMSWithID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.responseSMSccResponse IBBAV.WSTedexis.M4WSIntSRPortType.responseSMScc(IBBAV.WSTedexis.responseSMSccRequest request) {
            return base.Channel.responseSMScc(request);
        }
        
        public int responseSMScc(string passport, string password, string countryCode, string number, string text, string messageID) {
            IBBAV.WSTedexis.responseSMSccRequest inValue = new IBBAV.WSTedexis.responseSMSccRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.countryCode = countryCode;
            inValue.number = number;
            inValue.text = text;
            inValue.messageID = messageID;
            IBBAV.WSTedexis.responseSMSccResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).responseSMScc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSccResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMScc(IBBAV.WSTedexis.sendSMSccRequest request) {
            return base.Channel.sendSMScc(request);
        }
        
        public int sendSMScc(string passport, string password, string countryCode, string number, string text) {
            IBBAV.WSTedexis.sendSMSccRequest inValue = new IBBAV.WSTedexis.sendSMSccRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.countryCode = countryCode;
            inValue.number = number;
            inValue.text = text;
            IBBAV.WSTedexis.sendSMSccResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMScc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSWithIDccResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMSWithIDcc(IBBAV.WSTedexis.sendSMSWithIDccRequest request) {
            return base.Channel.sendSMSWithIDcc(request);
        }
        
        public int sendSMSWithIDcc(string passport, string password, string countryCode, string number, string text) {
            IBBAV.WSTedexis.sendSMSWithIDccRequest inValue = new IBBAV.WSTedexis.sendSMSWithIDccRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.countryCode = countryCode;
            inValue.number = number;
            inValue.text = text;
            IBBAV.WSTedexis.sendSMSWithIDccResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMSWithIDcc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IBBAV.WSTedexis.sendSMSResponse IBBAV.WSTedexis.M4WSIntSRPortType.sendSMS(IBBAV.WSTedexis.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string passport, string password, string number, string text) {
            IBBAV.WSTedexis.sendSMSRequest inValue = new IBBAV.WSTedexis.sendSMSRequest();
            inValue.passport = passport;
            inValue.password = password;
            inValue.number = number;
            inValue.text = text;
            IBBAV.WSTedexis.sendSMSResponse retVal = ((IBBAV.WSTedexis.M4WSIntSRPortType)(this)).sendSMS(inValue);
            return retVal.@return;
        }
    }
}
