//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsErrores {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsErroresSoap", Namespace="http://tempuri.org/")]
    public partial class WsErrores : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BDI_ErrorGetByCodigo_NemoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsErrores() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsErrores_WsErrores;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BDI_ErrorGetByCodigo_NemoCompletedEventHandler BDI_ErrorGetByCodigo_NemoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BDI_ErrorGetByCodigo_Nemo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BDI_ErrorGetByCodigo_Nemo(int codError, string sistema) {
            object[] results = this.Invoke("BDI_ErrorGetByCodigo_Nemo", new object[] {
                        codError,
                        sistema});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BDI_ErrorGetByCodigo_NemoAsync(int codError, string sistema) {
            this.BDI_ErrorGetByCodigo_NemoAsync(codError, sistema, null);
        }
        
        /// <remarks/>
        public void BDI_ErrorGetByCodigo_NemoAsync(int codError, string sistema, object userState) {
            if ((this.BDI_ErrorGetByCodigo_NemoOperationCompleted == null)) {
                this.BDI_ErrorGetByCodigo_NemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBDI_ErrorGetByCodigo_NemoOperationCompleted);
            }
            this.InvokeAsync("BDI_ErrorGetByCodigo_Nemo", new object[] {
                        codError,
                        sistema}, this.BDI_ErrorGetByCodigo_NemoOperationCompleted, userState);
        }
        
        private void OnBDI_ErrorGetByCodigo_NemoOperationCompleted(object arg) {
            if ((this.BDI_ErrorGetByCodigo_NemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BDI_ErrorGetByCodigo_NemoCompleted(this, new BDI_ErrorGetByCodigo_NemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BDI_ErrorGetByCodigo_NemoCompletedEventHandler(object sender, BDI_ErrorGetByCodigo_NemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BDI_ErrorGetByCodigo_NemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BDI_ErrorGetByCodigo_NemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591