//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsFavoritos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsFavoritosSoap", Namespace="http://tempuri.org/")]
    public partial class WsFavoritos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PreguntaIBSByPRE_PreguntaIBSIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback FailedFavoritosDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback FailedFavoritosAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback FailedFavoritosGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogPreguntasFavoritosAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogPreguntasFavoritosGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiliadoFavoritosGetByAfiliadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiliadoFavoritosGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiliadoFavoritosDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AfiliadoFavoritosAddUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TipoFavoritoGetOneOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsFavoritos() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsFavoritos_WsFavoritos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PreguntaIBSByPRE_PreguntaIBSIdCompletedEventHandler PreguntaIBSByPRE_PreguntaIBSIdCompleted;
        
        /// <remarks/>
        public event FailedFavoritosDeleteCompletedEventHandler FailedFavoritosDeleteCompleted;
        
        /// <remarks/>
        public event FailedFavoritosAddCompletedEventHandler FailedFavoritosAddCompleted;
        
        /// <remarks/>
        public event FailedFavoritosGetCompletedEventHandler FailedFavoritosGetCompleted;
        
        /// <remarks/>
        public event LogPreguntasFavoritosAddCompletedEventHandler LogPreguntasFavoritosAddCompleted;
        
        /// <remarks/>
        public event LogPreguntasFavoritosGetCompletedEventHandler LogPreguntasFavoritosGetCompleted;
        
        /// <remarks/>
        public event AfiliadoFavoritosGetByAfiliadoCompletedEventHandler AfiliadoFavoritosGetByAfiliadoCompleted;
        
        /// <remarks/>
        public event AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventHandler AfiliadoFavoritosGrupoGetByAfiliadoCompleted;
        
        /// <remarks/>
        public event AfiliadoFavoritosGetCompletedEventHandler AfiliadoFavoritosGetCompleted;
        
        /// <remarks/>
        public event AfiliadoFavoritosDeleteCompletedEventHandler AfiliadoFavoritosDeleteCompleted;
        
        /// <remarks/>
        public event AfiliadoFavoritosAddUpdateCompletedEventHandler AfiliadoFavoritosAddUpdateCompleted;
        
        /// <remarks/>
        public event TipoFavoritoGetOneCompletedEventHandler TipoFavoritoGetOneCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PreguntaIBSByPRE_PreguntaIBSId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PreguntaIBSByPRE_PreguntaIBSId(int PRE_PreguntaIBSId) {
            object[] results = this.Invoke("PreguntaIBSByPRE_PreguntaIBSId", new object[] {
                        PRE_PreguntaIBSId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PreguntaIBSByPRE_PreguntaIBSIdAsync(int PRE_PreguntaIBSId) {
            this.PreguntaIBSByPRE_PreguntaIBSIdAsync(PRE_PreguntaIBSId, null);
        }
        
        /// <remarks/>
        public void PreguntaIBSByPRE_PreguntaIBSIdAsync(int PRE_PreguntaIBSId, object userState) {
            if ((this.PreguntaIBSByPRE_PreguntaIBSIdOperationCompleted == null)) {
                this.PreguntaIBSByPRE_PreguntaIBSIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPreguntaIBSByPRE_PreguntaIBSIdOperationCompleted);
            }
            this.InvokeAsync("PreguntaIBSByPRE_PreguntaIBSId", new object[] {
                        PRE_PreguntaIBSId}, this.PreguntaIBSByPRE_PreguntaIBSIdOperationCompleted, userState);
        }
        
        private void OnPreguntaIBSByPRE_PreguntaIBSIdOperationCompleted(object arg) {
            if ((this.PreguntaIBSByPRE_PreguntaIBSIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PreguntaIBSByPRE_PreguntaIBSIdCompleted(this, new PreguntaIBSByPRE_PreguntaIBSIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FailedFavoritosDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FailedFavoritosDelete(long nAF_Id) {
            object[] results = this.Invoke("FailedFavoritosDelete", new object[] {
                        nAF_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FailedFavoritosDeleteAsync(long nAF_Id) {
            this.FailedFavoritosDeleteAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void FailedFavoritosDeleteAsync(long nAF_Id, object userState) {
            if ((this.FailedFavoritosDeleteOperationCompleted == null)) {
                this.FailedFavoritosDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFailedFavoritosDeleteOperationCompleted);
            }
            this.InvokeAsync("FailedFavoritosDelete", new object[] {
                        nAF_Id}, this.FailedFavoritosDeleteOperationCompleted, userState);
        }
        
        private void OnFailedFavoritosDeleteOperationCompleted(object arg) {
            if ((this.FailedFavoritosDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FailedFavoritosDeleteCompleted(this, new FailedFavoritosDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FailedFavoritosAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FailedFavoritosAdd(long nAF_Id) {
            object[] results = this.Invoke("FailedFavoritosAdd", new object[] {
                        nAF_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FailedFavoritosAddAsync(long nAF_Id) {
            this.FailedFavoritosAddAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void FailedFavoritosAddAsync(long nAF_Id, object userState) {
            if ((this.FailedFavoritosAddOperationCompleted == null)) {
                this.FailedFavoritosAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFailedFavoritosAddOperationCompleted);
            }
            this.InvokeAsync("FailedFavoritosAdd", new object[] {
                        nAF_Id}, this.FailedFavoritosAddOperationCompleted, userState);
        }
        
        private void OnFailedFavoritosAddOperationCompleted(object arg) {
            if ((this.FailedFavoritosAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FailedFavoritosAddCompleted(this, new FailedFavoritosAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FailedFavoritosGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FailedFavoritosGet(long nAF_Id) {
            object[] results = this.Invoke("FailedFavoritosGet", new object[] {
                        nAF_Id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FailedFavoritosGetAsync(long nAF_Id) {
            this.FailedFavoritosGetAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void FailedFavoritosGetAsync(long nAF_Id, object userState) {
            if ((this.FailedFavoritosGetOperationCompleted == null)) {
                this.FailedFavoritosGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFailedFavoritosGetOperationCompleted);
            }
            this.InvokeAsync("FailedFavoritosGet", new object[] {
                        nAF_Id}, this.FailedFavoritosGetOperationCompleted, userState);
        }
        
        private void OnFailedFavoritosGetOperationCompleted(object arg) {
            if ((this.FailedFavoritosGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FailedFavoritosGetCompleted(this, new FailedFavoritosGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogPreguntasFavoritosAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogPreguntasFavoritosAdd(long nAF_Id, int numeroPregunta, string respuestaCorrecta) {
            object[] results = this.Invoke("LogPreguntasFavoritosAdd", new object[] {
                        nAF_Id,
                        numeroPregunta,
                        respuestaCorrecta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogPreguntasFavoritosAddAsync(long nAF_Id, int numeroPregunta, string respuestaCorrecta) {
            this.LogPreguntasFavoritosAddAsync(nAF_Id, numeroPregunta, respuestaCorrecta, null);
        }
        
        /// <remarks/>
        public void LogPreguntasFavoritosAddAsync(long nAF_Id, int numeroPregunta, string respuestaCorrecta, object userState) {
            if ((this.LogPreguntasFavoritosAddOperationCompleted == null)) {
                this.LogPreguntasFavoritosAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogPreguntasFavoritosAddOperationCompleted);
            }
            this.InvokeAsync("LogPreguntasFavoritosAdd", new object[] {
                        nAF_Id,
                        numeroPregunta,
                        respuestaCorrecta}, this.LogPreguntasFavoritosAddOperationCompleted, userState);
        }
        
        private void OnLogPreguntasFavoritosAddOperationCompleted(object arg) {
            if ((this.LogPreguntasFavoritosAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogPreguntasFavoritosAddCompleted(this, new LogPreguntasFavoritosAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogPreguntasFavoritosGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] LogPreguntasFavoritosGet(long nAF_Id) {
            object[] results = this.Invoke("LogPreguntasFavoritosGet", new object[] {
                        nAF_Id});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void LogPreguntasFavoritosGetAsync(long nAF_Id) {
            this.LogPreguntasFavoritosGetAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void LogPreguntasFavoritosGetAsync(long nAF_Id, object userState) {
            if ((this.LogPreguntasFavoritosGetOperationCompleted == null)) {
                this.LogPreguntasFavoritosGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogPreguntasFavoritosGetOperationCompleted);
            }
            this.InvokeAsync("LogPreguntasFavoritosGet", new object[] {
                        nAF_Id}, this.LogPreguntasFavoritosGetOperationCompleted, userState);
        }
        
        private void OnLogPreguntasFavoritosGetOperationCompleted(object arg) {
            if ((this.LogPreguntasFavoritosGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogPreguntasFavoritosGetCompleted(this, new LogPreguntasFavoritosGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiliadoFavoritosGetByAfiliado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AfiliadoFavoritosGetByAfiliado(long nAF_Id) {
            object[] results = this.Invoke("AfiliadoFavoritosGetByAfiliado", new object[] {
                        nAF_Id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGetByAfiliadoAsync(long nAF_Id) {
            this.AfiliadoFavoritosGetByAfiliadoAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGetByAfiliadoAsync(long nAF_Id, object userState) {
            if ((this.AfiliadoFavoritosGetByAfiliadoOperationCompleted == null)) {
                this.AfiliadoFavoritosGetByAfiliadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiliadoFavoritosGetByAfiliadoOperationCompleted);
            }
            this.InvokeAsync("AfiliadoFavoritosGetByAfiliado", new object[] {
                        nAF_Id}, this.AfiliadoFavoritosGetByAfiliadoOperationCompleted, userState);
        }
        
        private void OnAfiliadoFavoritosGetByAfiliadoOperationCompleted(object arg) {
            if ((this.AfiliadoFavoritosGetByAfiliadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiliadoFavoritosGetByAfiliadoCompleted(this, new AfiliadoFavoritosGetByAfiliadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiliadoFavoritosGrupoGetByAfiliado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AfiliadoFavoritosGrupoGetByAfiliado(long nAF_Id, int tipoFavoritoId) {
            object[] results = this.Invoke("AfiliadoFavoritosGrupoGetByAfiliado", new object[] {
                        nAF_Id,
                        tipoFavoritoId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGrupoGetByAfiliadoAsync(long nAF_Id, int tipoFavoritoId) {
            this.AfiliadoFavoritosGrupoGetByAfiliadoAsync(nAF_Id, tipoFavoritoId, null);
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGrupoGetByAfiliadoAsync(long nAF_Id, int tipoFavoritoId, object userState) {
            if ((this.AfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted == null)) {
                this.AfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted);
            }
            this.InvokeAsync("AfiliadoFavoritosGrupoGetByAfiliado", new object[] {
                        nAF_Id,
                        tipoFavoritoId}, this.AfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted, userState);
        }
        
        private void OnAfiliadoFavoritosGrupoGetByAfiliadoOperationCompleted(object arg) {
            if ((this.AfiliadoFavoritosGrupoGetByAfiliadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiliadoFavoritosGrupoGetByAfiliadoCompleted(this, new AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiliadoFavoritosGet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AfiliadoFavoritosGet(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento) {
            object[] results = this.Invoke("AfiliadoFavoritosGet", new object[] {
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGetAsync(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento) {
            this.AfiliadoFavoritosGetAsync(nAF_Id, TipoFavoritoId, NumeroInstrumento, null);
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosGetAsync(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento, object userState) {
            if ((this.AfiliadoFavoritosGetOperationCompleted == null)) {
                this.AfiliadoFavoritosGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiliadoFavoritosGetOperationCompleted);
            }
            this.InvokeAsync("AfiliadoFavoritosGet", new object[] {
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento}, this.AfiliadoFavoritosGetOperationCompleted, userState);
        }
        
        private void OnAfiliadoFavoritosGetOperationCompleted(object arg) {
            if ((this.AfiliadoFavoritosGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiliadoFavoritosGetCompleted(this, new AfiliadoFavoritosGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiliadoFavoritosDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AfiliadoFavoritosDelete(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento) {
            object[] results = this.Invoke("AfiliadoFavoritosDelete", new object[] {
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosDeleteAsync(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento) {
            this.AfiliadoFavoritosDeleteAsync(nAF_Id, TipoFavoritoId, NumeroInstrumento, null);
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosDeleteAsync(long nAF_Id, int TipoFavoritoId, string NumeroInstrumento, object userState) {
            if ((this.AfiliadoFavoritosDeleteOperationCompleted == null)) {
                this.AfiliadoFavoritosDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiliadoFavoritosDeleteOperationCompleted);
            }
            this.InvokeAsync("AfiliadoFavoritosDelete", new object[] {
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento}, this.AfiliadoFavoritosDeleteOperationCompleted, userState);
        }
        
        private void OnAfiliadoFavoritosDeleteOperationCompleted(object arg) {
            if ((this.AfiliadoFavoritosDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiliadoFavoritosDeleteCompleted(this, new AfiliadoFavoritosDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AfiliadoFavoritosAddUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AfiliadoFavoritosAddUpdate(int accion, long nAF_Id, int TipoFavoritoId, string NumeroInstrumento, string CedulaRif, string BankId, string Beneficiario, string Descripcion, string TipoTarjetaCredito, string Email) {
            object[] results = this.Invoke("AfiliadoFavoritosAddUpdate", new object[] {
                        accion,
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento,
                        CedulaRif,
                        BankId,
                        Beneficiario,
                        Descripcion,
                        TipoTarjetaCredito,
                        Email});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosAddUpdateAsync(int accion, long nAF_Id, int TipoFavoritoId, string NumeroInstrumento, string CedulaRif, string BankId, string Beneficiario, string Descripcion, string TipoTarjetaCredito, string Email) {
            this.AfiliadoFavoritosAddUpdateAsync(accion, nAF_Id, TipoFavoritoId, NumeroInstrumento, CedulaRif, BankId, Beneficiario, Descripcion, TipoTarjetaCredito, Email, null);
        }
        
        /// <remarks/>
        public void AfiliadoFavoritosAddUpdateAsync(int accion, long nAF_Id, int TipoFavoritoId, string NumeroInstrumento, string CedulaRif, string BankId, string Beneficiario, string Descripcion, string TipoTarjetaCredito, string Email, object userState) {
            if ((this.AfiliadoFavoritosAddUpdateOperationCompleted == null)) {
                this.AfiliadoFavoritosAddUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAfiliadoFavoritosAddUpdateOperationCompleted);
            }
            this.InvokeAsync("AfiliadoFavoritosAddUpdate", new object[] {
                        accion,
                        nAF_Id,
                        TipoFavoritoId,
                        NumeroInstrumento,
                        CedulaRif,
                        BankId,
                        Beneficiario,
                        Descripcion,
                        TipoTarjetaCredito,
                        Email}, this.AfiliadoFavoritosAddUpdateOperationCompleted, userState);
        }
        
        private void OnAfiliadoFavoritosAddUpdateOperationCompleted(object arg) {
            if ((this.AfiliadoFavoritosAddUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AfiliadoFavoritosAddUpdateCompleted(this, new AfiliadoFavoritosAddUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TipoFavoritoGetOne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TipoFavoritoGetOne(int tipofavoritoId) {
            object[] results = this.Invoke("TipoFavoritoGetOne", new object[] {
                        tipofavoritoId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TipoFavoritoGetOneAsync(int tipofavoritoId) {
            this.TipoFavoritoGetOneAsync(tipofavoritoId, null);
        }
        
        /// <remarks/>
        public void TipoFavoritoGetOneAsync(int tipofavoritoId, object userState) {
            if ((this.TipoFavoritoGetOneOperationCompleted == null)) {
                this.TipoFavoritoGetOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTipoFavoritoGetOneOperationCompleted);
            }
            this.InvokeAsync("TipoFavoritoGetOne", new object[] {
                        tipofavoritoId}, this.TipoFavoritoGetOneOperationCompleted, userState);
        }
        
        private void OnTipoFavoritoGetOneOperationCompleted(object arg) {
            if ((this.TipoFavoritoGetOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TipoFavoritoGetOneCompleted(this, new TipoFavoritoGetOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void PreguntaIBSByPRE_PreguntaIBSIdCompletedEventHandler(object sender, PreguntaIBSByPRE_PreguntaIBSIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PreguntaIBSByPRE_PreguntaIBSIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PreguntaIBSByPRE_PreguntaIBSIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void FailedFavoritosDeleteCompletedEventHandler(object sender, FailedFavoritosDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FailedFavoritosDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FailedFavoritosDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void FailedFavoritosAddCompletedEventHandler(object sender, FailedFavoritosAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FailedFavoritosAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FailedFavoritosAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void FailedFavoritosGetCompletedEventHandler(object sender, FailedFavoritosGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FailedFavoritosGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FailedFavoritosGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogPreguntasFavoritosAddCompletedEventHandler(object sender, LogPreguntasFavoritosAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogPreguntasFavoritosAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogPreguntasFavoritosAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void LogPreguntasFavoritosGetCompletedEventHandler(object sender, LogPreguntasFavoritosGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogPreguntasFavoritosGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogPreguntasFavoritosGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AfiliadoFavoritosGetByAfiliadoCompletedEventHandler(object sender, AfiliadoFavoritosGetByAfiliadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiliadoFavoritosGetByAfiliadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiliadoFavoritosGetByAfiliadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventHandler(object sender, AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiliadoFavoritosGrupoGetByAfiliadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AfiliadoFavoritosGetCompletedEventHandler(object sender, AfiliadoFavoritosGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiliadoFavoritosGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiliadoFavoritosGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AfiliadoFavoritosDeleteCompletedEventHandler(object sender, AfiliadoFavoritosDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiliadoFavoritosDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiliadoFavoritosDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AfiliadoFavoritosAddUpdateCompletedEventHandler(object sender, AfiliadoFavoritosAddUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AfiliadoFavoritosAddUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AfiliadoFavoritosAddUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TipoFavoritoGetOneCompletedEventHandler(object sender, TipoFavoritoGetOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TipoFavoritoGetOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TipoFavoritoGetOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591