//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IBBAV.WsNotif_IBP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsNotif_IBP_asmxSoap", Namespace="http://tempuri.org/")]
    public partial class WsNotif_IBP_asmx : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotificacionAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestinoDelOperationCompleted;
        
        private System.Threading.SendOrPostCallback DestinoAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificacionExpiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotificacionVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaDestPeriodoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaConexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaPaisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleNotificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestriccionAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestriccionVerifyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsNotif_IBP_asmx() {
            this.Url = global::IBBAV.Properties.Settings.Default.IBBAV_WsNotif_IBP_WsNotif_IBP_asmx;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NotificacionAddCompletedEventHandler NotificacionAddCompleted;
        
        /// <remarks/>
        public event DestinoDelCompletedEventHandler DestinoDelCompleted;
        
        /// <remarks/>
        public event DestinoAddCompletedEventHandler DestinoAddCompleted;
        
        /// <remarks/>
        public event NotificacionExpiryCompletedEventHandler NotificacionExpiryCompleted;
        
        /// <remarks/>
        public event NotificacionVerifyCompletedEventHandler NotificacionVerifyCompleted;
        
        /// <remarks/>
        public event ValidaDestPeriodoCompletedEventHandler ValidaDestPeriodoCompleted;
        
        /// <remarks/>
        public event ValidaConexionCompletedEventHandler ValidaConexionCompleted;
        
        /// <remarks/>
        public event ListaPaisesCompletedEventHandler ListaPaisesCompleted;
        
        /// <remarks/>
        public event DetalleNotificacionCompletedEventHandler DetalleNotificacionCompleted;
        
        /// <remarks/>
        public event RestriccionAddCompletedEventHandler RestriccionAddCompleted;
        
        /// <remarks/>
        public event RestriccionVerifyCompletedEventHandler RestriccionVerifyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NotificacionAdd(long nAF_Id, string inicio, string fin, string destino, string TipoIns, string NumIns) {
            object[] results = this.Invoke("NotificacionAdd", new object[] {
                        nAF_Id,
                        inicio,
                        fin,
                        destino,
                        TipoIns,
                        NumIns});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NotificacionAddAsync(long nAF_Id, string inicio, string fin, string destino, string TipoIns, string NumIns) {
            this.NotificacionAddAsync(nAF_Id, inicio, fin, destino, TipoIns, NumIns, null);
        }
        
        /// <remarks/>
        public void NotificacionAddAsync(long nAF_Id, string inicio, string fin, string destino, string TipoIns, string NumIns, object userState) {
            if ((this.NotificacionAddOperationCompleted == null)) {
                this.NotificacionAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificacionAddOperationCompleted);
            }
            this.InvokeAsync("NotificacionAdd", new object[] {
                        nAF_Id,
                        inicio,
                        fin,
                        destino,
                        TipoIns,
                        NumIns}, this.NotificacionAddOperationCompleted, userState);
        }
        
        private void OnNotificacionAddOperationCompleted(object arg) {
            if ((this.NotificacionAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificacionAddCompleted(this, new NotificacionAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestinoDel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DestinoDel(long nAF_Id, long destinoID) {
            object[] results = this.Invoke("DestinoDel", new object[] {
                        nAF_Id,
                        destinoID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DestinoDelAsync(long nAF_Id, long destinoID) {
            this.DestinoDelAsync(nAF_Id, destinoID, null);
        }
        
        /// <remarks/>
        public void DestinoDelAsync(long nAF_Id, long destinoID, object userState) {
            if ((this.DestinoDelOperationCompleted == null)) {
                this.DestinoDelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestinoDelOperationCompleted);
            }
            this.InvokeAsync("DestinoDel", new object[] {
                        nAF_Id,
                        destinoID}, this.DestinoDelOperationCompleted, userState);
        }
        
        private void OnDestinoDelOperationCompleted(object arg) {
            if ((this.DestinoDelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestinoDelCompleted(this, new DestinoDelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DestinoAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DestinoAdd(long nAF_Id, System.DateTime inicio, System.DateTime fin, string destino) {
            object[] results = this.Invoke("DestinoAdd", new object[] {
                        nAF_Id,
                        inicio,
                        fin,
                        destino});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DestinoAddAsync(long nAF_Id, System.DateTime inicio, System.DateTime fin, string destino) {
            this.DestinoAddAsync(nAF_Id, inicio, fin, destino, null);
        }
        
        /// <remarks/>
        public void DestinoAddAsync(long nAF_Id, System.DateTime inicio, System.DateTime fin, string destino, object userState) {
            if ((this.DestinoAddOperationCompleted == null)) {
                this.DestinoAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDestinoAddOperationCompleted);
            }
            this.InvokeAsync("DestinoAdd", new object[] {
                        nAF_Id,
                        inicio,
                        fin,
                        destino}, this.DestinoAddOperationCompleted, userState);
        }
        
        private void OnDestinoAddOperationCompleted(object arg) {
            if ((this.DestinoAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DestinoAddCompleted(this, new DestinoAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionExpiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NotificacionExpiry(long nAF_Id) {
            object[] results = this.Invoke("NotificacionExpiry", new object[] {
                        nAF_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NotificacionExpiryAsync(long nAF_Id) {
            this.NotificacionExpiryAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void NotificacionExpiryAsync(long nAF_Id, object userState) {
            if ((this.NotificacionExpiryOperationCompleted == null)) {
                this.NotificacionExpiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificacionExpiryOperationCompleted);
            }
            this.InvokeAsync("NotificacionExpiry", new object[] {
                        nAF_Id}, this.NotificacionExpiryOperationCompleted, userState);
        }
        
        private void OnNotificacionExpiryOperationCompleted(object arg) {
            if ((this.NotificacionExpiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificacionExpiryCompleted(this, new NotificacionExpiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotificacionVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool NotificacionVerify(long nAF_Id) {
            object[] results = this.Invoke("NotificacionVerify", new object[] {
                        nAF_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void NotificacionVerifyAsync(long nAF_Id) {
            this.NotificacionVerifyAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void NotificacionVerifyAsync(long nAF_Id, object userState) {
            if ((this.NotificacionVerifyOperationCompleted == null)) {
                this.NotificacionVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotificacionVerifyOperationCompleted);
            }
            this.InvokeAsync("NotificacionVerify", new object[] {
                        nAF_Id}, this.NotificacionVerifyOperationCompleted, userState);
        }
        
        private void OnNotificacionVerifyOperationCompleted(object arg) {
            if ((this.NotificacionVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotificacionVerifyCompleted(this, new NotificacionVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaDestPeriodo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaDestPeriodo(long nAF_Id) {
            object[] results = this.Invoke("ValidaDestPeriodo", new object[] {
                        nAF_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaDestPeriodoAsync(long nAF_Id) {
            this.ValidaDestPeriodoAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void ValidaDestPeriodoAsync(long nAF_Id, object userState) {
            if ((this.ValidaDestPeriodoOperationCompleted == null)) {
                this.ValidaDestPeriodoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaDestPeriodoOperationCompleted);
            }
            this.InvokeAsync("ValidaDestPeriodo", new object[] {
                        nAF_Id}, this.ValidaDestPeriodoOperationCompleted, userState);
        }
        
        private void OnValidaDestPeriodoOperationCompleted(object arg) {
            if ((this.ValidaDestPeriodoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaDestPeriodoCompleted(this, new ValidaDestPeriodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaConexion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ValidaConexion() {
            object[] results = this.Invoke("ValidaConexion", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaConexionAsync() {
            this.ValidaConexionAsync(null);
        }
        
        /// <remarks/>
        public void ValidaConexionAsync(object userState) {
            if ((this.ValidaConexionOperationCompleted == null)) {
                this.ValidaConexionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaConexionOperationCompleted);
            }
            this.InvokeAsync("ValidaConexion", new object[0], this.ValidaConexionOperationCompleted, userState);
        }
        
        private void OnValidaConexionOperationCompleted(object arg) {
            if ((this.ValidaConexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaConexionCompleted(this, new ValidaConexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaPaises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListaPaises() {
            object[] results = this.Invoke("ListaPaises", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListaPaisesAsync() {
            this.ListaPaisesAsync(null);
        }
        
        /// <remarks/>
        public void ListaPaisesAsync(object userState) {
            if ((this.ListaPaisesOperationCompleted == null)) {
                this.ListaPaisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaPaisesOperationCompleted);
            }
            this.InvokeAsync("ListaPaises", new object[0], this.ListaPaisesOperationCompleted, userState);
        }
        
        private void OnListaPaisesOperationCompleted(object arg) {
            if ((this.ListaPaisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaPaisesCompleted(this, new ListaPaisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetalleNotificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DetalleNotificacion(long nAF_Id) {
            object[] results = this.Invoke("DetalleNotificacion", new object[] {
                        nAF_Id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleNotificacionAsync(long nAF_Id) {
            this.DetalleNotificacionAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void DetalleNotificacionAsync(long nAF_Id, object userState) {
            if ((this.DetalleNotificacionOperationCompleted == null)) {
                this.DetalleNotificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleNotificacionOperationCompleted);
            }
            this.InvokeAsync("DetalleNotificacion", new object[] {
                        nAF_Id}, this.DetalleNotificacionOperationCompleted, userState);
        }
        
        private void OnDetalleNotificacionOperationCompleted(object arg) {
            if ((this.DetalleNotificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleNotificacionCompleted(this, new DetalleNotificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RestriccionAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RestriccionAdd(long nAF_Id, string dirIP, string decimalIp, string instTipo, string instNum) {
            object[] results = this.Invoke("RestriccionAdd", new object[] {
                        nAF_Id,
                        dirIP,
                        decimalIp,
                        instTipo,
                        instNum});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RestriccionAddAsync(long nAF_Id, string dirIP, string decimalIp, string instTipo, string instNum) {
            this.RestriccionAddAsync(nAF_Id, dirIP, decimalIp, instTipo, instNum, null);
        }
        
        /// <remarks/>
        public void RestriccionAddAsync(long nAF_Id, string dirIP, string decimalIp, string instTipo, string instNum, object userState) {
            if ((this.RestriccionAddOperationCompleted == null)) {
                this.RestriccionAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestriccionAddOperationCompleted);
            }
            this.InvokeAsync("RestriccionAdd", new object[] {
                        nAF_Id,
                        dirIP,
                        decimalIp,
                        instTipo,
                        instNum}, this.RestriccionAddOperationCompleted, userState);
        }
        
        private void OnRestriccionAddOperationCompleted(object arg) {
            if ((this.RestriccionAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestriccionAddCompleted(this, new RestriccionAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RestriccionVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RestriccionVerify(long nAF_Id) {
            object[] results = this.Invoke("RestriccionVerify", new object[] {
                        nAF_Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RestriccionVerifyAsync(long nAF_Id) {
            this.RestriccionVerifyAsync(nAF_Id, null);
        }
        
        /// <remarks/>
        public void RestriccionVerifyAsync(long nAF_Id, object userState) {
            if ((this.RestriccionVerifyOperationCompleted == null)) {
                this.RestriccionVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestriccionVerifyOperationCompleted);
            }
            this.InvokeAsync("RestriccionVerify", new object[] {
                        nAF_Id}, this.RestriccionVerifyOperationCompleted, userState);
        }
        
        private void OnRestriccionVerifyOperationCompleted(object arg) {
            if ((this.RestriccionVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestriccionVerifyCompleted(this, new RestriccionVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void NotificacionAddCompletedEventHandler(object sender, NotificacionAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificacionAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificacionAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DestinoDelCompletedEventHandler(object sender, DestinoDelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestinoDelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestinoDelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DestinoAddCompletedEventHandler(object sender, DestinoAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DestinoAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DestinoAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void NotificacionExpiryCompletedEventHandler(object sender, NotificacionExpiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificacionExpiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificacionExpiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void NotificacionVerifyCompletedEventHandler(object sender, NotificacionVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotificacionVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotificacionVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ValidaDestPeriodoCompletedEventHandler(object sender, ValidaDestPeriodoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaDestPeriodoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaDestPeriodoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ValidaConexionCompletedEventHandler(object sender, ValidaConexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaConexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaConexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListaPaisesCompletedEventHandler(object sender, ListaPaisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaPaisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaPaisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void DetalleNotificacionCompletedEventHandler(object sender, DetalleNotificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleNotificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleNotificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RestriccionAddCompletedEventHandler(object sender, RestriccionAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestriccionAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestriccionAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RestriccionVerifyCompletedEventHandler(object sender, RestriccionVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestriccionVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestriccionVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591